name: Gradle Build (LifeSoul)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Use Gradle without needing a wrapper on your machine
      - name: Set up Gradle 8.9
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Build with Gradle (LifeSoul subfolder)
        working-directory: LifeSoul
        run: gradle build

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: lifesoul-jar
          path: build/libs/*.jar
